name: Manual Trigger

on:
  # 手动触发事件
  workflow_dispatch:
    inputs:
      GitUrlForKit:
        description: 'godwoken-kit -git url'
        default: 'https://github.com/RetricSu/godwoken-kicker.git'
      GitBranchForKit:
        description: 'godwoken-kit -git branch'
        default: 'compatibility-changes'
      StartGodwoken:
        description: 'start godwoken'
        default: 'true'
      TestScript:
        description: 'exec test case:1.test 2:test:gw_testnet_v1 3:test:bsc_test'
        default: 'test:gw_testnet_v1'
#    inputs:
#      logLevel:
#        description: 'Log level'
#        required: true
#        default: 'warning'
#      tags:
#        description: 'Test scenario tags'
#
# jobs:
#  printInputs:
#    runs-on: ubuntu-latest
#    steps:
#      - run: |
#          echo "GitUrlForKit level: ${{ github.event.inputs.GitUrlForKit }}"
#          echo "GitBranchForKit: ${{ github.event.inputs.GitBranchForKit }}"
#          echo "TestScript: ${{ toJson(github.event.TestScript) }}"


jobs:
  #  start-godwoken:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - run: echo "Part 1. Deploy Local Network of Godwoken"
  #      - name: Clone source code
  #        run: |
  #          git clone -b compatibility-changes https://github.com/RetricSu/godwoken-kicker.git
  #          cd godwoken-kicker
  #          ./kicker init
  #          ./kicker start
  #          ./kicker info
  #          ./kicker ps

  contract-tests:
    strategy:
      fail-fast: false
      matrix:
        net: ['testnet_v1']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: printInputs
        id: printInputs
        run: |
         echo "GitUrlForKit level: ${{ github.event.inputs.GitUrlForKit }}"
         echo "GitBranchForKit: ${{ github.event.inputs.GitBranchForKit }}"
         echo "TestScript: ${{ github.event.inputs.TestScript }}"
         echo "StartGodwoken: ${{ github.event.inputs.StartGodwoken }}"
        
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Node Cache
        uses: actions/cache@v2
        id: npm-and-yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ~/.npm
          key: ${{ runner.os }}-node_modules-${{ hashFiles('/home/runner/work/**/package-lock.json', '/home/runner/work/**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - run: echo "Part 2. Deploy Local Network of Godwoken"
      - name: Clone source code
        run: |
          if [ ${{ github.event.inputs.StartGodwoken }} == "true" ];then
            git clone -b ${{ github.event.inputs.GitBranchForKit }} ${{ github.event.inputs.GitUrlForKit }}
            cd godwoken-kicker
            ./kicker init
            ./kicker start
            ./kicker info
            ./kicker ps
            ./kicker ps web3
            ./kicker logs
            ./kicker logs web3
            ./kicker deposit 0xCD1d13450cFA630728D0390C99957C6948BF7d19 1000
            ./kicker deposit 0x0c1efcca2bcb65a532274f3ef24c044ef4ab6d73 1000
            ./kicker deposit 0x6DaF63D8411D6E23552658E3cFb48416A6A2CA78 1000
            cd ../
            curl http://localhost:8024 -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"web3_clientVersion","params": [],"id":1}'
          fi
      - name: Run tests
        id: runtest
        run: |
          npm install
          npm run ${{ github.event.inputs.TestScript }}
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: mocha Tests
          path: test-results.json
          reporter: mocha-json
